### ISSUE TITLE
Error: The path is not of legal form.

### ISSUE THREAD

**Issue by MPasadu** [kuanysh-nabiyev/RenameProjectVsExtension#10]
Trying to rename a project I get this error. 
"The path is not of legal form.
[callstack]
RenameCommand.cs:line 136"

**Comment by kuanysh-nabiyev** [comment]
@MPasadu 
can you send me print screen of callstack and write new name of a project?

**Comment by drunderscore** [comment]
![Stacktrace](https://image.prntscr.com/image/pFcB20oOTnCFXLx_LgzqJw.png)
Anything that is not the original name will cause this. Only tried it on a single solution, in a project with that one solution.

**Comment by kuanysh-nabiyev** [comment]
@electricman226 
I have 2 assumptions of the error:
1. your project folder path contains one of the following characters ", <, >, or |
2. your solution and project located on same folder level, that's .sln and .csproj files are located in one folder. 

If none of them is not true, can you send me unique name of the project? It is located in .sln file.
For example,
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ConsoleApp", "ConsoleApp\ConsoleApp.csproj", "{E463DDFF-D375-405B-B06F-E64DFED0F68F}".
Here the project unique name is ConsoleApp\ConsoleApp.csproj

**Comment by drunderscore** [comment]
It is a C++ project; I hadn't noticed that this was primarily a C# project tool. All project, solution, filter, and .cpp/.h files located in the same directory (not my choice, simply the way the original project was built).

![Project files](https://image.prntscr.com/image/sIIuzaGXSYeOXNpo-2IL-w.png)

**Comment by kuanysh-nabiyev** [comment]
@electricman226 I didn't test the extension on C++ projects. 
But you can try do to it and do it only under any VCS:
1. Close Visual studio.
2. Move your project (with related to project files) to serverplugin_empty folder 
3. Rename unique name in solution file.
FROM: 
Project("{GUID1}") = "serverplugin_empty", "serverplugin_empty .vcхproj", "{GUID2}".
TO:  
Project("{GUID1}") = "serverplugin_empty", "serverplugin_empty/serverplugin_empty .vcхproj", "{GUID2}".
4. Open Visual Studio and try to rename.
5. Close Visual Studio
6. Rename *.vcxproj.filters, *.vcxproj.vpc_crc.  I don't know what is it. I guess, something related to C++
7. Open Visual Studio

**Comment by MPasadu** [comment]
My project is a C# project.

![image](https://user-images.githubusercontent.com/29043682/32721442-d2c9ac6c-c866-11e7-842d-9e80bd8f69bc.png)

Doesn't matter which new name I choose - always fails.

> your solution and project located on same folder level, that's .sln and .csproj files are located in one folder.

That's the case! Any possible fix?

**Comment by kuanysh-nabiyev** [comment]
@MPasadu download and install the extension with fixed error from the following link [https://drive.google.com/open?id=1-aA0z-3ViX21yrRtMbkJ7bJ9jn7iaity](https://drive.google.com/open?id=1-aA0z-3ViX21yrRtMbkJ7bJ9jn7iaity).
@electricman226  it should work on C++ project too

Please, inform me about renaming result

**Comment by MPasadu** [comment]
No more error! Thank you!

**Comment by ghost** [comment]
Hi,

I have the same issue : C++ project, solution and project on the same level (but "It doesn't matter if project is located in solution folder (even for subfolder of solution folder) ") ... I see you closed the bug, but you did not update the version: 

Version | 2.1
-- | --
Last updated | ‎**9‎/‎21‎/‎2017**‎ ‎12‎:‎48‎:‎29
(https://marketplace.visualstudio.com/items?itemName=KuanyshNabiyev.FullRenameProject )

![capture](https://user-images.githubusercontent.com/30229510/35089490-5ea90fbc-fc37-11e7-95f2-dc0297eb6c47.PNG)

Thank you for the feedback

**Comment by ghost** [comment]
With the "Google drive" version it does not crash anymore, but ... it does nothing, even if the operation is successful. I reload and it just stays the same.

![capture](https://user-images.githubusercontent.com/30229510/35089859-653a7c66-fc38-11e7-959b-22cc8ce8e1bc.PNG)

**Comment by kuanysh-nabiyev** [comment]
@LiviuAndron I only tested the extension for C# project, but the code is generic for renaming any project type. In your case try to close and open Visual Studio. Sometimes Visual Studio does not reload the project after renaming. And don't forget to rename files which related to C++ only (f.e: *.filters). I didn't know about such files.

PS: I didn't update it, because people start to hate me because of updating extension after each small bug :)

**Comment by ghost** [comment]
Thank you for reply, but I do not have to continue - we have a cmake system now. 
You updated it four months ago.
