### ISSUE TITLE
can anyone help me rename this project ?

### ISSUE THREAD

**Issue by wongchunghim** [kuanysh-nabiyev/RenameProjectVsExtension#11]
1.change all Lau ho waiThomas to wongchunghim
2.change all 160179991 to 170138865
[please!!![]

[https://doc-00-8k-docs.googleusercontent.com/docs/securesc/fcjs3snadn9r83iats78l8snk9nns49g/57ostkfuqaqh65mmh3pkhfnfjliknt4h/1511596800000/11324005335961328067/12584170690735666054/1u2QzbBXs45zC9N2LnDSaKiu9K2BLD-of?e=download](url)

**Comment by wongchunghim** [comment]
https://doc-00-8k-docs.googleusercontent.com/docs/securesc/fcjs3snadn9r83iats78l8snk9nns49g/57ostkfuqaqh65mmh3pkhfnfjliknt4h/1511596800000/11324005335961328067/12584170690735666054/1u2QzbBXs45zC9N2LnDSaKiu9K2BLD-of?e=download

**Comment by kuanysh-nabiyev** [comment]
@wongchunghim I don't have access to file

**Comment by wongchunghim** [comment]
Here is the file.Thank you so much 

    Kuanysh <notifications@github.com> 於 2017年11月25日 (週六) 5:49 PM 寫道﹕
 

 @wongchunghim I don't have access to file—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   
 
|  | 不含病毒。www.avast.com  |

**Comment by kuanysh-nabiyev** [comment]
Sorry,but you didn't attach the file

**Comment by wongchunghim** [comment]
what can i do?

    Kuanysh <notifications@github.com> 於 2017年11月25日 (週六) 7:30 PM 寫道﹕
 

 Sorry,but you didn't attach the file—

**Comment by kuanysh-nabiyev** [comment]
Explain where is you problem in renaming a project.
Attach screenshot of the error if you get it. 

Try to find your problem in other issues

**Comment by wongchunghim** [comment]
https://files.fm/u/vd55zzz5

**Comment by wongchunghim** [comment]
Here is the file!!!!!

**Comment by wongchunghim** [comment]
1.change all Lau ho waiThomas to wongchunghim
2.change all 160179991 to 170138865
THANK!!!!!!!!!!

**Comment by kuanysh-nabiyev** [comment]
@wongchunghim you use vs2013. The extension was created for vs2017. Unfortunately you cannot use the extension in your project
