### ISSUE TITLE
Rename with changing namespaces fails always: Close all folders, text editors related to the project. Could not find part of the path

### ISSUE THREAD

**Issue by skylee91** [kuanysh-nabiyev/RenameProjectVsExtension#12]
![image](https://user-images.githubusercontent.com/5526164/33464191-19ab5158-d67c-11e7-8e03-99e47ced235b.png)

Note: I have closed all the folders and text editors but still got this error.

**Comment by kuanysh-nabiyev** [comment]
@skylee91 I noticed such error when the extension(with rename namespce option) is used for web applications. It is appeared because of security reasons of App_Data and wwwroot folders .
 - If you don't have any files in App_Data, you can remove App_Data and retry to rename a project.
 - If you have files in App_Data, move App_Data folder to another place and then return it 
 - If you have resharper, you can rename a project without 'rename namespace option' and then rename namespace using resharper. The 'rename namespace option' was created for non resharper users

In future release this bug will be fixed

**Comment by GaboDot** [comment]
@kuanysh-nabiyev Hi, before any other thing let me congratulate you for the nice extension.

I tried your suggested solution (removing / moving the App_Data folder) but it didn't work, after doing it and compiled the same error's window appears, I'm using VS2017 enterprise with an MVC5 project.

Do you have any other suggestion? 

I tested with C# console projects/apps and it worked perfectly.

**Comment by kuanysh-nabiyev** [comment]
@g4b0-88 thanks.
Can you attach your error as skylee91?

**Comment by GaboDot** [comment]
@kuanysh-nabiyev sure.
Here, no App_Data folder and build succeeded.
![screenshot_1](https://user-images.githubusercontent.com/8822582/34362196-328a39ae-ea37-11e7-9584-1aac0213a96a.png)
Here the error screenshot.
![screenshot_2](https://user-images.githubusercontent.com/8822582/34362197-338c8f8c-ea37-11e7-89b5-ff3e134afc64.png)

**Comment by kuanysh-nabiyev** [comment]
@g4b0-88 looking on your screenshot, error appears because of App_Code folder. 
Maybe App_Start folder will fire the same error. 
Tty to move them to another place, rename and then return

**Comment by GaboDot** [comment]
@kuanysh-nabiyev I got the following error:

![image](https://user-images.githubusercontent.com/8822582/34364073-bc4bd53e-ea47-11e7-913d-6cc3f38bfc78.png)

**Comment by kuanysh-nabiyev** [comment]
@g4b0-88 I propose that the project folder (SIPRES2019) is opened. 
Close it if it is opened and try to rename

**Comment by GaboDot** [comment]
@kuanysh-nabiyev  I already did it, after I saw it was opened, but got the same error.

**Comment by kuanysh-nabiyev** [comment]
@g4b0-88 maybe a file from the project is opened on any text editors (notepad, vscode)?
Try to close everything except Visual Studio

**Comment by kuanysh-nabiyev** [comment]
@g4b0-88 Is it fixed the error? 
Do you have folder (project, solution) permissions(modify, write)?

**Comment by GaboDot** [comment]
@kuanysh-nabiyev  sorry for the delay.

I got admin permissions, also VS is running as admin, nothing else than VS is opened:

![image](https://user-images.githubusercontent.com/8822582/34365315-9336568a-ea54-11e7-94e1-06684f4bc04e.png)

**Comment by kuanysh-nabiyev** [comment]
@g4b0-88 it is another error. I didn't see such error before. Error appeared when extension try to rename namespaces. I will try to find to investigate it on the current week. 
You could try to rename without rename namespaces option. And then rename namespaces manually by replacing old project name to new project name (you can read what to replace by clicking on Readme button). Thanks for reporting such (new to me) error

**Comment by kuanysh-nabiyev** [comment]
@g4b0-88 Did you rename the project?
