### ISSUE TITLE
Not updating namespaces in xaml files

### ISSUE THREAD

**Issue by GnoZ** [kuanysh-nabiyev/RenameProjectVsExtension#13]
After renaming a project with Renaming namespaces option checked, I noticed by rebuilding that my xaml files was not updated. Ctrl+Shift+H did the trick.

**Comment by kuanysh-nabiyev** [comment]
@DaGnoZ you are right. renaming namespace does not work on xaml files. It works only for .cs files. You can click on readme button (it is located after renaming checkbox) to read what is replaced.
If you have resharper you can use it for renaming namespaces. This option was created for non reshraper users
