### ISSUE TITLE
VS 2017 is not giving me the option to rename

### ISSUE THREAD

**Issue by Alex-Fairbank** [kuanysh-nabiyev/RenameProjectVsExtension#15]
I have installed the tool and enabled access and am running VS2017 as admin but the option to rename is not visible. I know this seems like a dumb issue and it is probably a simple fix but it really is a problem.

![extensions](https://user-images.githubusercontent.com/22645895/34637211-fb08d6de-f27e-11e7-8c2a-e4a5e2016b56.PNG)

**Comment by kuanysh-nabiyev** [comment]
@Alex-Fairbank what type of project did you tried to rename?

**Comment by Alex-Fairbank** [comment]
I am just trying to rename these two folders. In them contain my entire cs project and resources.
![rename capture](https://user-images.githubusercontent.com/22645895/34638006-1a2c8ef4-f291-11e7-9c5f-ec0bfec05071.PNG)

inside the folder is this
![inside of allinonemono](https://user-images.githubusercontent.com/22645895/34638035-7b085f3c-f291-11e7-96a4-c770fa535dad.PNG)

**Comment by kuanysh-nabiyev** [comment]
@Alex-Fairbank Is it website or web application?
To open FullRename dialog you need to right click on a project and under Rename menuitem you will see FullRename menu item 
![image](https://user-images.githubusercontent.com/5706213/34638094-f309e4a8-f2ee-11e7-863b-99d13dad6840.png)

**Comment by Alex-Fairbank** [comment]
Thankyou for responding in such a quick manner. This is not a web based application, I am trying to rename the folders that contain my project files. They are the namespace of the project as well. Would it be easier to send you the folder to give you a sense of the higherachy? 
![folders](https://user-images.githubusercontent.com/22645895/34643015-00018c82-f2eb-11e7-89b8-1c5906dd08d4.PNG)
![namespace](https://user-images.githubusercontent.com/22645895/34643020-174f0e00-f2eb-11e7-8474-9cc6487a5c07.PNG)

[AllInOneMono (2).zip](https://github.com/kuanysh-nabiyev/RenameProjectVsExtension/files/1609118/AllInOneMono.2.zip)

**Comment by kuanysh-nabiyev** [comment]
@Alex-Fairbank you should open solution, not a folder of the solution.
The extension renames folder by renaming project inside solution. That's, as you name project in dialog box of the extension, folder which contains the project will be same.
I cannot open the project of your attached solution, because it requires to install monogame stuff.

**Comment by Alex-Fairbank** [comment]
Hello once again I am unable to find the rename all feature. I am unfortunately unable to screenshot on school computers but when I select the project I am only shown the rename feature and not the rename all feature. Perhaps you can give it a try? If not I completely understand.



[AllInOneMono (3).zip](https://github.com/kuanysh-nabiyev/RenameProjectVsExtension/files/1612703/AllInOneMono.3.zip)

https://www.dropbox.com/home/MonoGame%20Setup

![rename](https://user-images.githubusercontent.com/22645895/34687336-6443bde0-f47c-11e7-9265-adc458f218d0.PNG)

**Comment by kuanysh-nabiyev** [comment]
@Alex-Fairbank I have renamed your project using extension
![image](https://user-images.githubusercontent.com/5706213/34691846-22462a2e-f4e8-11e7-8345-0e92c95608b9.png)

When I have tried to rename the project, I found error. The error appears when project folder and project name is not same (project folder is AllInOneMono while project name is AlexJFairbankA5).  You can rename project folder yourself(also need fix it in solution(.sln) file) or use attached project [AllInOneMono.zip](https://github.com/kuanysh-nabiyev/RenameProjectVsExtension/files/1613030/AllInOneMono.zip)

**Comment by Alex-Fairbank** [comment]
Ok Perfect thankyou!
