### ISSUE TITLE
"The method or operation is not implemented" error

### ISSUE THREAD

**Issue by LmG7119** [kuanysh-nabiyev/RenameProjectVsExtension#16]
I'm using VS 2017 Enterprise to develop ETL using SSIS. When I try to rename project/solution I get "The method or operation is not implemented" error.

**Comment by kuanysh-nabiyev** [comment]
@LeoG71 It is hard to say the reason of such error. Please, attach screen of the error

**Comment by LmG7119** [comment]
There is not much to it. Just "Ok" dialog with that error. Is there any
logging I can pull for you?

**Comment by kuanysh-nabiyev** [comment]
@LeoG71 I propose that the extension does not work for your type of project, because VS SDK does not implement some method(s) which the extension use for renaming project.
