### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by EAbychkov** [kuanysh-nabiyev/RenameProjectVsExtension#18]
![image](https://user-images.githubusercontent.com/1067550/35904131-943b413a-0c14-11e8-890b-1072b446a4b4.png)

**Comment by kuanysh-nabiyev** [comment]
@EAbychkov there is bug in renaming namespaces. Try to rename without rename namespace option. 
if use resharper or another renaming namespaces tools
