### ISSUE TITLE
Getting a Not Implemented exception when attempting to use

### ISSUE THREAD

**Issue by erancahana** [kuanysh-nabiyev/RenameProjectVsExtension#2]
After specifying new name and clicking OK, I'm getting a MessageBox for an exception and nothing happens.

![image](https://user-images.githubusercontent.com/7053082/29456061-96024b9e-83d9-11e7-82ea-29a03637f594.png)

**Comment by kuanysh-nabiyev** [comment]
can you write what type of project have you changed?

**Comment by puppetSpace** [comment]
I'm also getting the error.
![2018-01-29_150317](https://user-images.githubusercontent.com/14003064/35514421-621362ec-0506-11e8-845b-3c7785ef06e3.png)

I'm changing a .NET 4.5.2 class library project

**Comment by kuanysh-nabiyev** [comment]
@puppetSpace looking at you stack trace I propose that one or several of your projects does not have the FullName property. Please, write project type of all other projects.

**Comment by puppetSpace** [comment]
Other projects are:
- ASP.NET Web application Web.API
- Unit Test project

**Comment by kuanysh-nabiyev** [comment]
@puppetSpace may be because of Unit test project, but I am not sure. Try to unload the unit test project and then rename your class library project. Please, do it  under source control

**Comment by kuanysh-nabiyev** [comment]
@puppetSpace If it the renaming successful and unit test project references to class library, you need to change name of class library in unit test .csproj file (ProjectReference tag)

OR remove old reference and add new reference to class library
