### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by verysimplenick** [kuanysh-nabiyev/RenameProjectVsExtension#20]
![default](https://user-images.githubusercontent.com/922660/37177908-eae63e5c-2331-11e8-9d1a-8e232d1af3cc.png)

With or not renaming namespaces

**Comment by kuanysh-nabiyev** [comment]
@verysimplenick try to install the following version https://drive.google.com/file/d/1-aA0z-3ViX21yrRtMbkJ7bJ9jn7iaity/view
It has some fixes and may be fix your problem
