### ISSUE TITLE
Issue... everything is closed related to the project

### ISSUE THREAD

**Issue by rkeith213** [kuanysh-nabiyev/RenameProjectVsExtension#22]
![image](https://user-images.githubusercontent.com/38440218/38830233-3b0f58a6-4181-11e8-8b6f-6415b27f33bc.png)

Error occurs with and without namespace renaming

**Comment by kuanysh-nabiyev** [comment]
@rkeith213 https://github.com/kuanysh-nabiyev/RenameProjectVsExtension/issues/17 can help you in solving the problem
