### ISSUE TITLE
Project's filter file not being renamed

### ISSUE THREAD

**Issue by GeorgePimpleton** [kuanysh-nabiyev/RenameProjectVsExtension#23]
The project's directory & .vcxproj and .vcxproj.user files are being renamed correctly.  The .vcxproj.filters file is not being renamed.

**Comment by kuanysh-nabiyev** [comment]
@FurryGuy the extension doesn't rename *.filters file, because it's related only for C++ project and I didn't know about such file. 
To fix it, you should rename the file manually
