### ISSUE TITLE
extension on marketplace.visualstudio.com not found

### ISSUE THREAD

**Issue by danielscherzer** [kuanysh-nabiyev/RenameProjectVsExtension#24]
Hi,

thanks for your very usefull extensions. I did a repeair install of vs studio today and now I realized your extension is not anymore on the marketplace and the link on your github page (https://marketplace.visualstudio.com/items?itemName=KuanyshNabiyev.FullRenameProject) is not working.

**Comment by kuanysh-nabiyev** [comment]
@danielscherzer Hi, 
You are right, because of many negative reviews without contructive explanation, I removed it from marketplace. 
Thx, I have forgotten about readme file. It was updated.
https://github.com/kuanysh-nabiyev/RenameProjectVsExtension/blob/master/FullRenamer2017-11-13.vsix

**Comment by danielscherzer** [comment]
Thanks!
