### ISSUE TITLE
Not Implemented - Error

### ISSUE THREAD

**Issue by MPasadu** [kuanysh-nabiyev/RenameProjectVsExtension#26]
See error below:

https://imgur.com/a/p8g7X9P

Using the latest version of Visual Studio 2017 Pro. It's a .Net / C# project. The path looks like this:

...\ProjectName\ProjectName\ProjectName.csproj (**trying to rename this one**)  
...\ProjectName\ProjectName.Integration\ProjectName.Integration.csproj (integration tests project)  
...\ProjectName\ProjectName.Unit\ProjectName.Unit.csproj (unit tests project)  

I guess the problem could be that there is a folder above with the same name?

**Comment by kuanysh-nabiyev** [comment]
@MPasadu looking at your screenshot, I guess the problem is VS cannot get path to the one of the solution projects. May be your solution have another types of the projects, because of them the exception was occurred.
Try to unload them and use FullRename extension

**Comment by MPasadu** [comment]
@kuanysh-nabiyev

The solution has 100+ projects. But that was never a problem before, when I recall correctly.

**Comment by kuanysh-nabiyev** [comment]
@MPasadu the exception was thrown in VSIX API. I have one above assumption of the exception, because one of the users had the same exception as I remember. His solution had SSIS project. Please, check if there is(are) such projects in your solution

**Comment by MPasadu** [comment]
No, but there are also WiX setup projects in the solution (these are unloaded though)

**Comment by kuanysh-nabiyev** [comment]
@MPasadu try to install the following version of the extension. I hope it helps
https://expirebox.com/download/49684fcf9b5a31d12ed8061e9ece0cd7.html
