### ISSUE TITLE
Class namespace update

### ISSUE THREAD

**Issue by messengert** [kuanysh-nabiyev/RenameProjectVsExtension#3]
It would be nice to have the option to rename the namespace inside all the classes too.

**Comment by rujesh** [comment]
I faced the same issue with namespace in my VS2017 project.

**Comment by kuanysh-nabiyev** [comment]
@rujesh if you have resharper, please, use it for such task.
If you don't have resharper, you need to wait until my implementation of the task.

**Comment by kuanysh-nabiyev** [comment]
@messengert @rujesh The feture was implemented for C# projects. You can check it  by updating the extension

**Comment by rujesh** [comment]
First of all wonderful work with the rename extension.
I tested the updated version; it solved the namespace issue in the renamed project except for the using statements and occurrences of project name inside files in the renamed project.
I think you need to replace using and project name in NamespaceRenamer.ProjectFiles just the way you have done for NamespaceRenamer.SolutionFiles. I tried adding the logic there and it worked. Can you please confirm?

**Comment by kuanysh-nabiyev** [comment]
@rujesh thx. I understand you. I have forgotten about 'using' inside renamed project. 

'I tried adding the logic there and it worked. Can you please confirm?'
- I don't have any pull request from you to confirm it.

**Comment by rujesh** [comment]
I had tested it locally via the ConsoleApp. I have now created a pull request for it.

**Comment by kuanysh-nabiyev** [comment]
@rujesh thx. I have updated the extension

**Comment by rujesh** [comment]
I see 2.1 has the feature working properly,
