### ISSUE TITLE
Access to the path 'D:\Some\Path\Worker.csproj' is denied

### ISSUE THREAD

**Issue by kzrbill** [kuanysh-nabiyev/RenameProjectVsExtension#4]
Using Visual Studio 2017 Enterprise i'm getting "Access to the path 'D:\Some\Path\Worker.csproj'" is denied. See screen grab. The name of the project file was originally different as per screen grab. It seems the the Full Rename process itself is locking access to the file.

![renametoworker](https://user-images.githubusercontent.com/185562/30487286-ec233710-9a2a-11e7-8e3a-38f09ff47426.png)

**Comment by kuanysh-nabiyev** [comment]
@kzrbill Try to close all applications related to the project/solution. (f.e. notepad)

**Comment by kzrbill** [comment]
@kuanysh-nabiyev Thanks for getting back to me. No other applications are open relating to the solution. I did initially install RenameProjectVsExtension as a non-admin user then installed again as an admin user (I run VS under admin account). I will then re-install as admin user only to see if that fixes things.

**Comment by kzrbill** [comment]
@kuanysh-nabiyev reporting that machine restart and re-install of RenameProjectVsExtension does not fix this..

**Comment by kuanysh-nabiyev** [comment]
@kzrbill can you create new solution and try to rename a project in it?

**Comment by kuanysh-nabiyev** [comment]
@kzrbill does the same error occur for newly created solution?

**Comment by kuanysh-nabiyev** [comment]
@kzrbill or maybe problem with VS Enterprise edition. If you have colleague who has VS Enterprise edition, can you check it?
I have tested the extension only on VS Community Edition

**Comment by kuanysh-nabiyev** [comment]
@kzrbill I have reproduced your error. You should give write permission to the worker.csproj file

**Comment by kzrbill** [comment]
Yes that's it @kuanysh-nabiyev - thanks for investigating and apologies as this is non-issue with your VS extension. I have a wider issue with VS 2017 on Windows 10 putting project tree into a read only state.
