### ISSUE TITLE
Rename project from MYPROJECT to MYPROJECT.EXAMPLE fails

### ISSUE THREAD

**Issue by WizX20** [kuanysh-nabiyev/RenameProjectVsExtension#6]
Visual studio community edition 2017 15.3.5
Current (latest version) of rename from visual studio marketplace: 2.1

![image](https://user-images.githubusercontent.com/1008647/31316033-26176d04-ac25-11e7-926f-5feecc692ec7.png)

Steps to reproduce:
- Create a solution, MyThing1
- Create a new web project, also name it MyThing1 (namespace is MyThing1)
- Rename the project to MyThing1.App

**Comment by kuanysh-nabiyev** [comment]
@WizX20 I cannot reproduce the error even by following your steps.
I have search the following error message "source and destination path must be different" and found that it is appeared when new project name is same or difference in case (MyThing1 -> myThing1).
