### ISSUE TITLE
Error on attempting to rename project

### ISSUE THREAD

**Issue by mrfnord** [kuanysh-nabiyev/RenameProjectVsExtension#7]
Installed the extension in Visual Studio Enterprise 2017 15.2.26430.6

Opened solution with 3 projects, a .Net 4.6.1 c# class library, 4.6.1 c# WinForms test harness app, and 4.6.1 web application. Attempted to rename any of the projects, with or without namespace rename, all generated this error:

![image](https://user-images.githubusercontent.com/1631182/31504237-79c484cc-af37-11e7-9a1e-2cc4ba9c13a0.png)

Verified that no folders were open, no other apps than VS were open, no files were open (apart from the solution in the Solution Explorer) in VS. Closed and reopened VS, same problem. The fold path is 4 folders deep, with some folders having up to 20 characters, but nothing out of the ordinary for a namespaced project.

**Comment by kuanysh-nabiyev** [comment]
@mrfnord you are the second man who write me about such problem (https://github.com/kuanysh-nabiyev/RenameProjectVsExtension/issues/6). But I don't have any idea why it is appeared in your environment. 
I will try to reproduce the error

Can you write me current name and new name of a project?

**Comment by saf-itpro** [comment]
@kuanysh-nabiyev  I have the same exact issue on `VS2017`: Created a default `ASP.NET MVC Core` application. Nothing was added, it just the default web app that VS creates. Right clicked on the project name in VS, clicked on "`Full Rename`", got the exact same message shown in the screenshot in the  original post above.

**Comment by kuanysh-nabiyev** [comment]
@saf-itpro I cannot reproduce the error.
Please, write current name and new name of the project?
