### ISSUE TITLE
Access to path <path-to-project> is denied

### ISSUE THREAD

**Issue by robertnaum** [kuanysh-nabiyev/RenameProjectVsExtension#8]
I tried running this rename project on a Visual Studio Enterprise 2017 15.4 .  It game me an Access Denied error.  I tried running VS both as Administrator and non-Administrator.  Same error.  What kind of permissions is required for the folder?  

![image](https://user-images.githubusercontent.com/11302328/31529165-9956e622-afa5-11e7-998d-b2634e0a8b4c.png)

**Comment by kuanysh-nabiyev** [comment]
@robertnaum do you have write access to the folder?

**Comment by robertnaum** [comment]
OK, I changed the folder name a bit, it had "....C#" in the folder name and that seemed to allow it to proceed.  Now I'm getting the following error, same as other users..

![image](https://user-images.githubusercontent.com/11302328/31554653-34d991b0-b00c-11e7-8ce4-ef3a0e94ed5d.png)

**Comment by kuanysh-nabiyev** [comment]
@robertnaum other issue creators who have the same error didn't answer to you. 
Please, give the following information:
1. Folder name of the project
2. Current name of the project
3. New name of the project
