### ISSUE TITLE
NullReferenceException when attempting a project rename

### ISSUE THREAD

**Issue by ThatShawGuy** [kuanysh-nabiyev/RenameProjectVsExtension#9]
Getting the following error when attempting to rename one of my projects. I only have four files in this project. Two C# classes, packages.config, and a ruleset file. Also, I checked the Rename namespaces option.

![image](https://user-images.githubusercontent.com/5739911/31557481-e12d8fca-b016-11e7-9e73-179044dbfdde.png)

VS 2017 - Version 15.3.5
Project Target Framework: 4.6.1
Project Output Type: Class Library

**Comment by kuanysh-nabiyev** [comment]
@ThatShawGuy Looking at the error dialog hard to say where the problem, but I propose that one of the solution files (all projects files in solution) doesn't have 'FullPath' property (full path of a file). If I'm correct I think it's strange and surpize behaviour.  
The method that search all files in solution only calls when Rename namespaces option is checked.
Such file can be located at any project of the solution.

Please, check it is fixed the bug by downloading extension from the following link
[https://drive.google.com/open?id=0B520zNYNGOEbSTJERTJIYkNGd1E](url)
